<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <None Remove="fonts\VT323-Regular.ttf" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PlantTracker.Core\PlantTracker.Core.csproj" />
    <ProjectReference Include="..\PlantTracker.Data\PlantTracker.Data.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.WinUI.Notifications" Version="7.1.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.10">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="fonts\VT323-Regular.ttf" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

</Project>
